language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
notifications:
  email: false
sudo: required
services:
  - docker
script: 
  - awesome_bot README.md
  - docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`
  - awesome_bot README.md --white-list travis-ci